name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: |
           8.0.x
  
      - name: Print date
        run: (sleep 5 && echo "this is after sleeping 5 seconds, printed at $(date)") & echo "this is async, printed at $(date)"
        
      - name: Start API, run tests, kill API
        working-directory: ./NewsAPI
        run: (dotnet run --urls http://localhost:5000) & 
             (sleep 20 && cd ../NewsAPITests && dotnet test) & 
             (sleep 40 && kill -9 $(lsof -t -i:5000))
        env:
          pgconn: ${{secrets.pgconn}}